### ISSUE TITLE
mode emit event

### ISSUE THREAD

**Issue by rickihastings** [martynsmith/node-irc#136]
Does anyone think it's worth emitting a standard mode event when a MODE is recieved, in addition to the +mode and -mode.

I'm thinking an event that just emits the nick setting the mode, the channel and the message object. My reasoning for this is because I'm doing some advanced mode parsing and keeping track of channels modes/banlists outside of node-irc and to be honest the +mode and -mode events just don't really make it any easier. I'd rather work with the original string in a one time event.

**Comment by Jnull** [comment]
There are a few other bugs relating to MODE, until all those are referenced together, its going to be hard to make this enhancement.   I would either add the Enhancement label or close this.

**Comment by Jnull** [comment]
This honestly should be closed, as there are ways in which channels are tracked now, which makes this super obsolete, which may have a way to incorporate better ways of tracking through just using the raw message.

**Comment by jirwin** [comment]
Mode tracking has been greatly improved in #351. Closing for now.
