### ISSUE TITLE
Cannot pass MODE command with multiple arguments

### ISSUE THREAD

**Issue by Fauntleroy** [martynsmith/node-irc#147]
I'm not sure if I'm doing something wrong, or if there's a bug somewhere, but I can't seem to send MODE commands with multiple arguments, no matter how hard I try. Currently I'm trying:

```javascript
irc_client.send( 'mode', '#irchub2000', '+oo', 'irchub1 irchub2000' );
```

but all I get in return is and error:

```
>>> ERROR { prefix: 'zelazny.freenode.net',
  server: 'zelazny.freenode.net',
  command: 'err_nosuchnick',
  rawCommand: '401',
  commandType: 'error',
  args: [ 'irchub', 'irchub2000', 'irchub' ] } No such nick/channel 1360543249142
```

**Comment by yanickrochon** [comment]
The problem I see is that, somehow, a `:` is inserted in front of the last argument... don't know why.

From the documentation, giving OP access to a user would require to send

```
MODE #channel +o user1 user2 ...
```

But calling the client the way you do would send `MODE #irchub2000 +oo :irchub1 irchub2000`
