### ISSUE TITLE
Event listener ctcp-privmsg's "message" is empty

### ISSUE THREAD

**Issue by tiddle** [martynsmith/node-irc#207]
Using the event listener ctcp-privmsg, the message parameter is always returned empty.

from, to and text return values but message does not.

![ctcp-privmsg](https://f.cloud.github.com/assets/1088859/1597198/877b791e-530a-11e3-8221-5178d1278358.PNG)

**Comment by ward** [comment]
This was fixed in commit https://github.com/martynsmith/node-irc/commit/ec4985412be10a14d6b219f6b4005cdb04eb6691
