### ISSUE TITLE
With stripColors: true set, a post only containing control characters, such as color or bold crashes the library

### ISSUE THREAD

**Issue by flare561** [martynsmith/node-irc#218]
> var irc = new (require('irc')).Client('irc.testserver.com', 'test', {
> ...     channels: ['#test'], stripColors: true
> ...   });
> undefined

test client joins IRC, another user sends a message containing only a color code, with no other text

> /home/user/node_modules/irc/lib/irc.js:637
>                     throw err;
>                           ^
> TypeError: Cannot read property '0' of undefined
>     at Client.<anonymous> (/home/user/node_modules/irc/lib/irc.js:468:25)
>     at Client.EventEmitter.emit (events.js:95:17)
>     at /home/user/node_modules/irc/lib/irc.js:634:22
>     at Array.forEach (native)
>     at Socket.<anonymous> (/home/user/node_modules/irc/lib/irc.js:631:15)
>     at Socket.EventEmitter.emit (events.js:95:17)
>     at Socket.<anonymous> (_stream_readable.js:746:14)
>     at Socket.EventEmitter.emit (events.js:92:17)
>     at emitReadable_ (_stream_readable.js:408:10)
>     at emitReadable (_stream_readable.js:404:5)

test client crashes

**Comment by webcracy** [comment]
I'm also experiencing this same error but I can't pinpoint the reasons or the circumstances.

It's very hard to reproduce as it only happens 2-3 times in 35,000 messages received.

```
/Users/user/project/node_modules/irc/lib/irc.js:637
                    throw err;
                          ^
TypeError: Cannot read property '0' of undefined
    at Client.<anonymous> /Users/user/project/node_modules/irc/lib/irc.js:468:25)
    at Client.emit (events.js:107:17)
    at /Users/user/project/node_modules/irc/lib/irc.js:634:22
    at Array.forEach (native)
    at Socket.<anonymous> (/Users/user/project/node_modules/irc/lib/irc.js:631:15)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```
