### ISSUE TITLE
oper command

### ISSUE THREAD

**Issue by dimlife** [martynsmith/node-irc#234]
How to send oper command?
bot.send('oper','xxxx','yyyy'); - no resaults.

**Comment by Jnull** [comment]
Use Client.send - https://node-irc.readthedocs.org/en/latest/API.html#Client.send
Example:    client.send("mode", "#channel", "+o", 'Nickname');

Please Close.  Thanks!

**Comment by moshmage** [comment]
@Jnull I don't think he wants the `mode #channel +o nick` command, he wants the `/oper nickname password` command that lets you identify as a network admin;    
@dimlife Should be something like `Client.send('OPER','nick','password');

I'm not sure we should implement this as an alias, as it's clearly a `raw` command and should be dealt with via `Client.send()`; If we end up making an alias to this one we would have to make for every single command in the book - and that would turn this into a client - not a lib. imo.

**Comment by jirwin** [comment]
`Client.send()` should be used for this.
