### ISSUE TITLE
SASL over SSL never happens

### ISSUE THREAD

**Issue by martinb3** [martynsmith/node-irc#250]
@gsf @martynsmith per https://github.com/martynsmith/node-irc/pull/125

I don't seem to be able to use SASL over SSL with this patch. I get disconnected in this section of code, before the CAP ever gets sent: https://github.com/gsf/node-irc/blob/0dd7ac1af65b7d70f6c0b31fb17ddc659c3bc516/lib/irc.js#L621-L625

It seems like a PASS should not be sent while connecting over SSL (causing a disconnect) before SASL is attempted (or at least capabilities are read). Over SSL with SASL enabled, my logs come out like so:

```
29 Aug 12:48:20 - Sending irc NICK/USER
29 Aug 12:48:21 - SEND: PASS abc123zyx
29 Aug 12:48:22 - SEND: NICK nick_name
29 Aug 12:48:23 - SEND: USER my_user 8 * :nodeJS IRC client
29 Aug 12:48:24 - Unhandled message: { command: 'ERROR',
  rawCommand: 'ERROR',
  commandType: 'normal',
  args: [ 'Closing link: (~my_user@1.2.3.4) [Access denied by configuration]' ] }
29 Aug 12:48:24 - Connection got "close" event
```

(Notice how CAP never gets sent here in this log)

**Comment by filler** [comment]
I can confirm that SASL + IRC in `node-irc` renders `Access denied by Access denied by configuration` for me.  But I believe Im connecting to the same SASL+SSL endpoint as @martinb3 ... ;)

Meanwhile, SASL + SSL works against freenode just fine with the server + passwd subbed out.  Doh.

**Comment by jirwin** [comment]
This is working now. If it isn't actually working, please re-open and include details for your specific server responses.
