### ISSUE TITLE
0.3.x : 'nicknameinuse' event missing

### ISSUE THREAD

**Issue by centime** [martynsmith/node-irc#258]
Hi,
First, thank you for this lib, I've been using it a lot last year, in it's previous version 0.3.x

I see you rewrote most of it, so maybe my issue isn't anymore, but looking at my old project I saw a quick fix that I did back then, thought it was worth putting it here.

There is no 'nicknameinuse' event raised by the client when it tries to connect to the server.

The workaround I applied was very straightforward : 

in irc.js, around line 190, after : 

       case "err_nicknameinuse":
                if ( typeof(self.opt.nickMod) == 'undefined' )
                    self.opt.nickMod = 0;
                self.opt.nickMod++;
                self.send("NICK", self.opt.nick + self.opt.nickMod);
                self.nick = self.opt.nick + self.opt.nickMod;

just add :
               self.emit('nicknameinuse',self.opt.nick,self.nick);

Maybe some other parts of the code should reflect this change as well, but it worked and I didn't look any further.

**Comment by apeiron** [comment]
This looks like it's [already merged](https://github.com/martynsmith/node-irc/blob/master/lib/irc.js#L219-L225).
