### ISSUE TITLE
Loading self signed certs

### ISSUE THREAD

**Issue by DaveBlooman** [martynsmith/node-irc#262]
I want to use a self signed cert.pem file with node-irc, what do i need to pass to `secure ` in order for this to work.  Most of the examples of loading certs in node are using a key and a cert, can you use a single combined pem file with node-irc?

**Comment by jirwin** [comment]
Node requires that the `key` and `cert` be provided separately as part of the `tls` [API](http://nodejs.org/api/tls.html#tls_tls_connect_options_callback). `node-irc` passed the object that is defined as `opt.secure` to the tls `connect` function.

Good luck!
