### ISSUE TITLE
Client.whois on nick not in use crashes bot running with v.0.3.3

### ISSUE THREAD

**Issue by galgeek** [martynsmith/node-irc#267]
If we do a Client.whois(nick, callback) for a nick that's not currently in use, the bot crashes, in the node-irc code.

I don't see any clear indication that this has been fixed in v.0.3.5 or more recent updates, but maybe I'm missing something?

The error handler here: https://www.npmjs.com/package/irc#help-it-keeps-crashing- is already included.

**Comment by apeiron** [comment]
Hi @galgeek! I'm not able to reproduce your crash. This is what I see when the bot tries to whois a nonexistent nick:

```
8 Jan 19:02:02 - SEND: WHOIS nonexistent
ERROR: err_nosuchnick: apeirontest nonexistent No such nick/channel
```
Can you please provide the stack trace that you get in this case?

**Comment by galgeek** [comment]
Hi @apeiron!

Thanks for taking a look.

Here's what I get, connected to irc.mozilla.org...

ERROR: err_nosuchnick: _TestDayBot badnick No such nick/channel

/Users/bara/Dev/testdaybot/node_modules/irc/lib/irc.js:520
                    throw err;
                          ^
TypeError: Cannot read property 'nick' of undefined
    at Client.callbackWrapper (/Users/bara/Dev/testdaybot/node_modules/irc/lib/irc.js:666:22)
    at Client.emit (events.js:95:17)
    at Client.<anonymous> (/Users/bara/Dev/testdaybot/node_modules/irc/lib/irc.js:253:22)
    at Client.emit (events.js:95:17)
    at /Users/bara/Dev/testdaybot/node_modules/irc/lib/irc.js:517:22
    at Array.forEach (native)
    at Socket.<anonymous> (/Users/bara/Dev/testdaybot/node_modules/irc/lib/irc.js:514:15)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)

**Comment by apeiron** [comment]
The line numbers in your stack trace do not line up with either what is in git master or what is on npm. Can you verify the version of node-irc you have installed?

**Comment by galgeek** [comment]
package.json claims it's 0.3.3, looking here: 

https://github.com/mozilla/testdaybot/blob/master/node_modules/irc/package.json

**Comment by apeiron** [comment]
Ah, indeed that is out of date. 0.3.7 is the latest. Can you try updating and see if you still see that bug?

**Comment by galgeek** [comment]
Hi @apeiron!

I think I've got 0.3.7 installed appropriately in my set up, and hooray! it seems to fix the crashing bug, as well as another issue I've been having using Client.join...

Thanks again for taking a look, and thanks for the nudge to update!

**Comment by apeiron** [comment]
\o/
