### ISSUE TITLE
Many servers do not send a meaningful hostname in 001

### ISSUE THREAD

**Issue by masochist** [martynsmith/node-irc#288]
This was found during troubleshooting #286. On at least hybrid, perhaps other ircds, the 001 message does not include a meaningful hostmask for the user. This means that the max message length calculation is incorrect. We'll need to find a way to correctly calculate the value, possibly by issuing a `WHOIS self.nick`, likely in a `registered` event handler or something similar. I have seen a number of bots do this, and I know irssi does it at least. @jirwin, thoughts?

**Comment by Trinitas** [comment]
#203 looks like that will solve it

**Comment by philip-peterson** [comment]
We could do an rDNS lookup initially just to get a good guess, then if the server doesn't provide a good hostmask, do a WHOIS, perhaps?

**Comment by Jnull** [comment]
This is not closed, PR #386 was merged so this should be closed?

**Comment by LinuxMercedes** [comment]
PR #386 hasn't been merged yet.

**Comment by jirwin** [comment]
Fixed #386
