### ISSUE TITLE
Please add feature for IRCv3 message tags!

### ISSUE THREAD

**Issue by Bigmacbook** [martynsmith/node-irc#298]
There is data in the raw messages that i can't get with the current module. I going to need it real soon cause the system i'm working on is deprecating previous version of IRC really soon

Please I need IRCv3 update ASAP

This is why!
[Twitch IRCv3 Change](http://discuss.dev.twitch.tv/t/irc-v3-the-future/1121)

**Comment by Bigmacbook** [comment]
I mainly need support for message tags

**Comment by apeiron** [comment]
Hi,

The best, fastest way of ensuring the features you want get added quickly is to contribute them yourself. We'll be glad to help, but as you can see from the pull req and issue queues, we have enough other things to look at. There is already an issue for IRCv3 support, #237, so I am closing this as a duplicate.
