### ISSUE TITLE
[Question] Timestamps or how much time a user has been connected?

### ISSUE THREAD

**Issue by johnRivs** [martynsmith/node-irc#321]
**Is there a way to retrieve the timestamp when a user joins a channel?**

Let's say I want to give 'points' according to how much time you've been connected. You'd be able to say !points to check yours.

Ideally, the bot would check the current time, substract the time when you joined and then do the math to know how many points you have.

**If the bot knew how much time a user has been connected**, it would be even easier. Is that available with node-irc?

If neither of those features are available, I guess I can store locally the currect time on user join.

**Comment by Jnull** [comment]
Since, a signification amount of time has passed I'm guessing that there is no functionality for time stamps currently. 

I suggest we close this.

**Comment by jirwin** [comment]
The bot only knows what it can see. You could easily keep track of when a user joins and parts on your own. I don't believe there is any IRC specific mechanism to get the timed join on a channel.
