### ISSUE TITLE
Error with node-icu-charset-detector

### ISSUE THREAD

**Issue by parkr** [martynsmith/node-irc#327]
Not supported on Heroku, and it doesn't seem to like newer versions of Node (v0.11/12). I think it's on the old v8 API. How is this package used? Can it be removed?

**Comment by jirwin** [comment]
It should be listed as an optional dependency, so `npm install` will still succeed if it isn't available, although it may warn. Is this not the case?

**Comment by parkr** [comment]
Oh, yes! it does seem to work here. 

```text
npm WARN optional dep failed, continuing node-icu-charset-detector@0.0.7
```

Is its functionality needed for anything crucial?

**Comment by jirwin** [comment]
It is for an optional feature for converting a server's encoding from UTF-8 to something else. You can enable it by using the encoding option in the configuration used to create a client(https://github.com/martynsmith/node-irc/blob/master/lib/irc.js#L58).

If you don't specify this option, the module is never used.

Cheers!
