### ISSUE TITLE
parse message TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by flipflopsimsommer** [martynsmith/node-irc#331]
from time to time when i start my app i get this error, so i guess it happens turing the authendification prozess.
i use freenode and login with password and set __sasl__ to __true__

    node_modules/irc/lib/parse_message.js:39
    message.command = match[1];

using the debug option didn't show any additnal data.

    iojs version 1-3.1
    npm version 2.5.1
    node-irc 0.3.9

**Comment by trevoranderson** [comment]
I've gotten this as well, but not just at start-up. Wrapping lines 39-40 in an "if(match)" seems to at least avoid crashing there. 

For reproduction purposes, match is null if line==="".

**Comment by aivot-on** [comment]
I assume this is the same issue as https://github.com/martynsmith/node-irc/issues/325 ?

**Comment by brentnk** [comment]
#318 has addressed this issue but has not been pushed to npm.  If you use the latest version from Github the issue should be resolved.
