### ISSUE TITLE
Update node-icu-charset-detector version for nodejs 0.12 compatibility

### ISSUE THREAD

**Issue by dbellavista** [martynsmith/node-irc#332]
node_modules/node-icu-charset-detector version `0.0.7` fails to build in node `0.12`. Update to current stable version `0.1.0` would solve the problem.

**Comment by jirwin** [comment]
Please submit a PR bumping the version in package.json

**Comment by jirwin** [comment]
Version `0.3.12` was published with node `0.12` support
