### ISSUE TITLE
Call stack size exceeded

### ISSUE THREAD

**Issue by trevoranderson** [martynsmith/node-irc#337]
D:\****************\node_modules\irc\lib\irc.js:945
    var part = words.substring(0, cutPos);
                     ^
RangeError: Maximum call stack size exceeded

This happens when maxLength is NaN, if something is "said" before maxlinelength is updated.

**Comment by philip-peterson** [comment]
Is there a specific scenario where a message might need to be sent before the RPL_WELCOME message is received?

**Comment by ward** [comment]
This was fixed alongside bug #419 by commit https://github.com/martynsmith/node-irc/commit/ce2bf24d914ec94912ab6b99dd8efd661a0f2c6e.
