### ISSUE TITLE
Connection to ZNC times out

### ISSUE THREAD

**Issue by Kuchiru** [martynsmith/node-irc#339]
Hello,

I cant quite provide you with specifics on this because your irclib is initiated by another project (which is dead) but i made sure it had the latest version of it.
I set the details to connect to the ZNC in irc.js with self signed certs true and secure true, the rest is default.
It connects to the ZNC and responds but about 3 to 15 (this varies a  lot) minutes later the connection times out.
If i connect directly to any network that is not ZNC it will remain connected indefinitely, also if i connect to my ZNC from any other client it will remain connected.

What am i doing wrong ?

Edit: logs

NodeIRC Log:
20 Mar 09:18:08 - Sending irc NICK/USER
20 Mar 09:18:08 - SEND: PASS omitted
20 Mar 09:18:09 - SEND: NICK Index
20 Mar 09:18:09 - SEND: USER index 8 \* :nodeJS IRC client
20 Mar 09:18:09 - MODE: Index sets mode: +ix
20 Mar 09:18:10 - SEND: PRIVMSG nickserv :identify 
20 Mar 09:18:10 - GOT NOTICE from "NickServ": "Syntax: IDENTIFY password"
20 Mar 09:18:10 - GOT NOTICE from "NickServ": "/msg NickServ HELP IDENTIFY for more information."
20 Mar 09:18:10 - SEND: JOIN #omitted
20 Mar 09:18:11 - SEND: MODE #omitted
20 Mar 09:25:03 - SEND: PONG ZNC
20 Mar 09:29:33 - SEND: PONG ZNC
20 Mar 09:34:34 - SEND: PONG ZNC
timeout

ZNC Log:
[2015-03-20 09:18:09] [sbuser] connected to ZNC from 195.154._._
[2015-03-20 09:37:34] [sbuser] disconnected from ZNC from 195.154._._

**Comment by aspett** [comment]
Also having this problem. Trying to debug at this time.
