### ISSUE TITLE
Can node-irc determine who is a mod?

### ISSUE THREAD

**Issue by ayatojhans** [martynsmith/node-irc#340]
I'm using node-irc on twitch.tv, which has an IRC based chat. When I connect via another IRC client, it properly shows the mods, so I'm assuming twitch is providing the info.

**Is there a way to retrieve the list of mods or check if a certain user is a mod?**

**Comment by sim642** [comment]
There's a dictionary of user channel modes in `client.chans['#channel'].users` where `client` is your node-irc `Client` object, have a look at that.

**Comment by ayatojhans** [comment]
No luck :/

Returns an object with the users like this:
```json
{ guitar_gamer: '',
  flem7825: '',
  steven2116: '',
  tallon4496: '',
  dekrullevaar: '',
  jonmarsten: '' }
```

**Comment by jirwin** [comment]
As an example, check out how I do it with my IRC bot at https://github.com/jirwin/treslek/blob/master/lib/treslek.js#L114.

**Comment by ayatojhans** [comment]
I think it's just how Twitch.tv handles his chat. Neither of those methods find a `@` on a mod's name.

Thanks for the help though.

**Comment by DanPantry** [comment]
Twitch.tv should have allowances for checking who is a mod or not. I'm also working on a twitch bot.

http://help.twitch.tv/customer/portal/articles/1302780-twitch-irc

````
JOIN: Opening a Chat Room & Obtaining a User List
Usage: JOIN #channelname

Notes:
After a successful JOIN, the following will take place:

You will be sent a list of users that are currently in the channel.
A number of MODEs will be set from the jtv user to signify that a user can moderate chat. Users that can moderate chat are are defined as Channel Moderators, Admin's and Staff.
< JOIN #channelname
> JOIN #channelname
> 353: = #channelname nickname nickname2 nickname3 nickname4 anotherNickname
> 353: = #channelname nickname25 nickname26 nicknameN
> 366: #channelname End of /NAMES list
> jtv MODE #channelname +o channel_moderator
> jtv MODE #channelname +o channel_moderator2
> jtv MODE #channelname +o staff_user
> jtv MODE #channelname +o twitch_global_mod_user
````

**Comment by ayatojhans** [comment]
Just switched to http://www.schmoopiie.com/docs/twitch-irc/
