### ISSUE TITLE
Document 'selfMessage' from #17

### ISSUE THREAD

**Issue by jhr007** [martynsmith/node-irc#349]
I just found #17 and noticed adding emit(selfMessage) was not in the [documentation](https://node-irc.readthedocs.org/en/latest/API.html).

Also... Semantically, I think this event would be a better service if it was moved to client.send .... 

Thoughts?

**Comment by jhr007** [comment]
I just noticed that emit('selfMessage') has been moved to _speak, but it still might be better in prototype.send. 

I think the purpose of selfMessage is to give an event that lets irc consumers debug outbound messages.

**Comment by jirwin** [comment]
The docs have been updated with `selfMessage`. While I was reviewing the doc change, I also thought that it should be in `client.send`. I'll take a closer look and get back to you.

**Comment by jirwin** [comment]
I pushed a PR to change this: https://github.com/martynsmith/node-irc/pull/353

**Comment by jhr007** [comment]
Thanks for the quick update. 

What do you think about an event like 'sendAll'  that could be used to tap into all outgoing messages? e.g. Modes, joins, parts...

The following probably deserves another issue, but thought I'd ask here first. 
In the essence of better, "self" in  selfMessage / selfNotice would be more intuitive/semantic if it was prefixed send. 

In defense of this point, when the debug option is set, `SEND: ` is added to outgoing debugging messages. 

Changing selfMessage to sendMessage would be a breaking change, unless .on & .addListener were wrapped to replace selfMessage with sendMessage and give a deprecation warning 'use sendMessage instead of selfMessage'. Then in a later release remove the wrapper. 

Just thinking out loud. 

Thanks again for documentation

**Comment by jirwin** [comment]
@jhr007 I like it. I'll make a new issue for standardizing events and debug logs for everything the client sends.
