### ISSUE TITLE
Update Client.chans on change MODE

### ISSUE THREAD

**Issue by yanickrochon** [martynsmith/node-irc#361]
When changing MODE on the client, the value of `client.chans` is not being updated.

For example, after joining a particular channel (ex: `#foo`), we get `client.chans['#foo'].mode;` to output `+cnt`. Now, if I give OP status to the client in that channel, the value will not change for that channel. It should get updated automatically.

**Comment by sim642** [comment]
Modes `+cnt` are channel modes, OP status `+o` is an user mode in a channel and is linked to a specific user. Have a look at `client.chans['#foo'].users['bar']` for OP status.

**Comment by yanickrochon** [comment]
Thank you! Indeed, this works!
