### ISSUE TITLE
Trying to make a bot and can't figure out how to kick and do other op tasks

### ISSUE THREAD

**Issue by awesomenessispure** [martynsmith/node-irc#363]
I am trying to make a bot that can kick people. I am using http://pastebin.com/X7Firevp currently. Instead of kicking the person when i type !kick NAME it puts it as a chat message to the chan. How can I go about fixing this.

**Comment by Timer** [comment]
You must actually use the IRC command KICK, irc clients are what provide you with the `/kick` syntactical sugar.
`KICK <channel> <client> [<message>]`

**Comment by sim642** [comment]
`bot.send('KICK', channel, nick, message);` should work

**Comment by Jnull** [comment]
These are viable solutions.  Please close this ticket.  Thanks!

**Comment by Jnull** [comment]
Please close this issue. Thanks!
