### ISSUE TITLE
Send CustomCommand to server

### ISSUE THREAD

**Issue by anonprophet** [martynsmith/node-irc#367]
i have pvpgn server (a server game), i want my bot use custom command
/nullinfo

```
client.addListener('pm', function(nick, message) {
    //console.log('Got private message from %s: %s', nick, message);
    if (message == '!sd') {
    	client.say(['#crew'], '/nullinfo long messages goes here');
    };
});
```

but the code above just say in the channel '' /nullinfo statsdota update ''
, how to make it send that command to server ?

something like ``/raw nullinfo`` in mIRC

**Comment by Wolvan** [comment]
You can access the underlying socket directly with client.conn. Then you can just do client.conn.write("nullinfo\r\n") and you should be all set

**Comment by Jnull** [comment]
Please use Client.send as it is said to be better than Client.conn: https://node-irc.readthedocs.org/en/latest/API.html#Client.send

Please accept as a viable answer and close.  Thanks!

**Comment by jirwin** [comment]
+1
