### ISSUE TITLE
Error undefined nick

### ISSUE THREAD

**Issue by anonprophet** [martynsmith/node-irc#371]
in events `'message#channel'`

if username contain symbol something like ``~`` and ``.``

it will return `undefined nick` error

**Comment by anonprophet** [comment]
thx fixed

im added that 2 symbol in parse_messages.js

``match = message.prefix.match(/^([_a-zA-Z0-9\[\]\\`^{}|-]*)(!([^@]+)@(.*))?$/);``

**Comment by ZAZmaster** [comment]
For support Russian nicknames add in parse_messages.js - А-Яа-яёЁ
match = message.prefix.match(/^([_a-zA-ZА-Яа-яёЁ0-9\[\]\\`~.^{}|-]*)(!([^@]+)@(.*))?$/);
