### ISSUE TITLE
User MODE changes are not being received in +MODE/-MODE handlers

### ISSUE THREAD

**Issue by Darkhogg** [martynsmith/node-irc#374]
In the current state of the library, user modes are not received by *any* event handlers (other than `raw`, of course).

My bot reacts to some user mode changes (especially `+r`), and treating them as regular `MODE` commands would be nice.

It seems that [this line](https://github.com/martynsmith/node-irc/blob/master/lib/irc.js#L255) is preventing it, I'm not sure if on purpose.

**Comment by Jnull** [comment]
Ya, mode needs to be cleaned up a bit to remove duplicate lines and redundant parsing,  I'm not sure what 'prefixForMode' is for, any idea?

**Comment by Jnull** [comment]
After a looking the line you referred its in anticipation of when the bot first joins the channel and gets a message (i.e.  MODE: nodebot sets mode: +iwRTxv) 

The line:  `if (!channel) break;`  looks like it should be  `if (!channel) return;`  because its breaking out of the entire for loop instead of allowing the next iteration.

**Comment by Darkhogg** [comment]
@Jnull An `if (!channel) return` would prevent the entire function from continuing. That `break` actually only affects the internal `case`.

**Comment by Jnull** [comment]
@Darkhogg, you're right i mixed up my break and my return, i just realized this is probably working because i only set one listener mode and not the other -mode when i was testing last night, so i thought i was running into a problem, which was just phantom.  i think modes are working fine then.

**Comment by jirwin** [comment]
Can you please try and see if the new events added in #351 solve this for you? Closing this for now as I believe it will.
