### ISSUE TITLE
can't get chat messages

### ISSUE THREAD

**Issue by kylonx** [martynsmith/node-irc#384]
Hi!
I tried to get the chat messages, but I can't see the messages in the console... Why?

> var net = require('irc');
var io = require('socket.io');
var formatter = require('dateformat');
var now = new Date;

>io.listen(1337);
log("Starting bot...");

>bot.addListener('error', function(message) {
	console.error('ERROR: %s: %s', message.command, message.args.join(' '));
});

>//GET MESSAGES
bot.addListener('message', function(from, to, text, msg) {
	log(from);
	log(to);
	log(msg);
	log(text);
});

>//IF USER JOINED TO THE BROADCAST => LOG
bot.addListener('join', function(channel, user) {
	log(user + " joined");
});

>//DISCONNECT
bot.addListener('part', function(channel, who, reason) {
    console.log('«%s» has left %s: %s', who, channel, reason);
});

>//IF USER GOT KICKED BY OP
bot.addListener('kick', function(channel, who, by, reason) {
    console.log('«%s» was kicked from %s by %s: %s', who, channel, by, reason);
});

>//CHECK IF BOT CONNECTED TO IRC CHAT
bot.addListener('connect', function(retryCount, callback) {
	log("Successfully connected!");
})										

console output:
>18 Jul 22:13:14 - Starting bot...
18 Jul 22:13:14 - Sending irc NICK/USER
18 Jul 22:13:14 - SEND: NICK :xxx
18 Jul 22:13:14 - SEND: USER xxxxx 8 * :xxx
18 Jul 22:13:14 - Successfully connected!
18 Jul 22:13:14 - SEND: JOIN :#xxxx
18 Jul 22:13:14 - xxxx joined
18 Jul 22:13:15 - SEND: MODE :#xxxx

**Comment by BirkhoffLee** [comment]
debug mode not on

**Comment by Jnull** [comment]
log is not defined or function or a command.    

Please close.
