### ISSUE TITLE
speak function bug, can't compile

### ISSUE THREAD

**Issue by BirkhoffLee** [martynsmith/node-irc#388]
node-irc version 0.3.12

Stack trace: http://pastebin.com/VhsiiEZ8

My code: http://pastebin.com/8qZzBnag

Any solution?

**Comment by Booster2ooo** [comment]
I think it's a matter of timing. The say method is called before the bot is connected or joined the channel. As there is no "connected" event, I think you should use the join event, and, only when the bot joined the channel, try to send the message.

Client.addListener("join#ysitd", function(channel, nick, message) {
    if(nick == config.botName) {
        Client.say( channel, "hello" ); // No more error
    }
});

**Comment by BirkhoffLee** [comment]
Working solution. Thanks very much.
