### ISSUE TITLE
Howto use node-irc within webchat?

### ISSUE THREAD

**Issue by ghost** [martynsmith/node-irc#391]
I'm building a webchat for our site to connect to IRC,

Do I need to use node-irc with another package for it to work as a webchat?

I see lots using socket.io, is it needed or can it be done with just node-irc?

Is there a simple example of it working in a webchat environment with multiple users?

Thanks for any help, I'm new to Node :)

**Comment by Jnull** [comment]
Not sure i understand, 

node-irc works with socket.io fine, if you need to turn this into a webchat, then you only need to use the client object as you declare it throughout your code.

**Comment by ircer** [comment]
Sorry I don't understand, is there an example of node-irc with socket.io?

I searched online but the projects on GitHub doing so are very dead, with outdated versions...

**Comment by moshmage** [comment]
ircer - a browser cannot handle TCP/IP sockets; If you want to use this as a web-application (served from the web) you'll have to setup node-irc as a man-in-the-middle listening for websockets connection; When said connection happens, node-irc triggers a new Client, connects to the irc, and uses the websocket to send information back and forth from/to the user

**Comment by Jnull** [comment]
Yes, a web application is required. 

@ircer:  you may want to look into using node "express" is a common npm package for hosting web applications.  e.g.   node-irc <-> express <-> webchat
