### ISSUE TITLE
quit event provides wrong channel information

### ISSUE THREAD

**Issue by 910JQK** [martynsmith/node-irc#398]
(v0.3.12)

 'quit'
function (nick, reason, channels, message) { }

*channels* is always all the channels which the client is in, not the channels which both the client and the quitted user are in.

**Comment by Jnull** [comment]
I made a PR for this issue, if its approved it will fix this issue at the next release, which should be very soon.

**Comment by jaredkipe** [comment]
A most sensible fix.
https://github.com/martynsmith/node-irc/pull/359/commits

**Comment by jirwin** [comment]
Fixed in #448
