### ISSUE TITLE
Not enough parameters'

### ISSUE THREAD

**Issue by anonprophet** [martynsmith/node-irc#416]
i just want my bot whisper ``!unhost`` only, but its give me error

```
17 Oct 17:07:42 - SEND: PRIVMSG dota-1 !unhost
error:  { prefix: 'sg02.xxx.id',
  server: 'sg02.xxx.id',
  command: 'err_needmoreparams',
  rawCommand: '461',
  commandType: 'error',
  args: [ 'DOTAHOST', 'PRIVMSG', 'Not enough parameters' ] }
```

what i must todo ?

**Comment by moshmage** [comment]
I have no clue what you just said, @anonprophet - care to explain it with more words?

**Comment by anonprophet** [comment]
sorry,
i want my bot whisper to user `dota-1` with message `!unhost`
but got error Not enough parameters
```
error:  { prefix: 'sg02.xxx.id',
  server: 'sg02.xxx.id',
  command: 'err_needmoreparams',
  rawCommand: '461',
  commandType: 'error',
  args: [ 'DOTAHOST', 'PRIVMSG', 'Not enough parameters' ] }
```

its ask my to add more text like `!unhost something` to fix this
but i just want my bot to whisper `!unhost`

**Comment by moshmage** [comment]
And what is the code you're using to do this?

**Comment by anonprophet** [comment]
```
case '!unhost':
if (inArray(allowner, nick)) {
	if (owner['dota-1'].toLowerCase() == nick) {
		client.say('dota-1', '!unhost');
	} else if (owner['dota-2'].toLowerCase() == nick) {
		client.say('dota-2', '!unhost');
	} else if (owner['dota-3'].toLowerCase() == nick) {
		client.say('dota-3', '!unhost');
	} else if (owner['dota-4'].toLowerCase() == nick) {
		client.say('dota-4', '!unhost');
	} else if (owner['dota-5'].toLowerCase() == nick) {
		client.say('dota-5', '!unhost');
	}
}
break;
```
this enough ? or i must post full code

**Comment by moshmage** [comment]
That's weird. This shouldn't be happening. Are you *sure* this is where the error is coming from?

**Comment by anonprophet** [comment]
Yes, as u can see first post
```17 Oct 17:07:42 - SEND: PRIVMSG dota-1 !unhost```
everytime i send that, its return
```
error:  { prefix: 'sg02.xxx.id',
  server: 'sg02.xxx.id',
  command: 'err_needmoreparams',
  rawCommand: '461',
  commandType: 'error',
  args: [ 'DOTAHOST', 'PRIVMSG', 'Not enough parameters' ] }
```

and i check `dota-1` its not receive the message

**Comment by moshmage** [comment]
Well, I really don't know how that could be happening. Can you share the irc server on which that is happening so I can try and figure out what's up?

**Comment by anonprophet** [comment]
where i can PM u access to my server?
bcoz its a pvpgn server https://github.com/pvpgn/pvpgn-server

i need pm u port, username and password

**Comment by moshmage** [comment]
pm me on moshmage@hmamail.com and I'll see what's what over the weekend.

**Comment by anonprophet** [comment]
@moshmage im already PM u the access, are u already check it ?
thanks

**Comment by moshmage** [comment]
@anonprophet It seems that it's a bug on the pvpgn part, I did get the same error as you - but only when connected to that server. I tried the same code on 3 servers, yours was the only one that gave that error.

**Comment by anonprophet** [comment]
is there other ways to send one word ? besides `.say` command ?

**Comment by Jnull** [comment]
May want to try these: 

Client.notice(target, message)
Client.send(command, arg1, arg2, ...)
Client.conn() deperciated -use Client.send() is said to be better. 

https://node-irc.readthedocs.org/en/latest/API.html#client

**Comment by moshmage** [comment]
Either what @Jnull said or you could try and go to the pvpgn github and report an issue.
You can always just change the receiving end code to match a two-word command.
