### ISSUE TITLE
node-irc with express/socket.io

### ISSUE THREAD

**Issue by ircer** [martynsmith/node-irc#417]
I'm building a web chat using node-irc.

I'm new to express/node.js/socket.io in general so please excuse any bad mistakes, but I'm following the documentation on the socket.io website as well as the node-irc documentation on here and Read The Docs.

index.js:

```
io.on('connection', function(socket){
  var client = new irc.Client('localhost', 'myNick', {
      channels: ['#webchat'],
  });

  client.addListener('message', function (from,to,message) {
    io.emit('message', message);
  });

  socket.on('disconnect', function(){
  });
});
```

index.html:

```
    <script>
      var socket = io();

      socket.on('message', function(message){
        $('#messages').append('<p>' +  message + '</p>');
      });
    </script>
```

But in `#messages` I see each message 3 times, why is this?

`3hi ya13hi ya13hi ya03Welcome Dimitra 03Welcome Dimitra 03Welcome Dimitra`

**Comment by Jnull** [comment]
This is because every time a webclient connects to the websocket, its re-initializing a brand new node-irc bot, including the 'addListener'. You may not see see the other two bots join, because they all have the same nick, but only left with the symptom of three messages 1/per each bot.  You probably just loaded the page to your web application and then refreshed twice.  If you can, I'd recommend putting the client object as a global instead of inside the websocket initialization.

**Comment by ircer** [comment]
@Jnull I want each user who connects to have their own connection so for example 100 users can open the page and it creates 100 connections. I guess I'm understanding it wrong. Can you point me in the right direction?

**Comment by Jnull** [comment]
you probably want something Jerry rigged like this: 
```
var user_id = 0; 
io.on('connection', function(socket){
user_id++; 
  var client = new irc.Client('localhost', 'myNick' + user_id, {
      channels: ['#webchat'],
  });

  client.addListener('message', function (from,to,message) {
    io.emit('message', message);
  });

  socket.on('disconnect', function(){
  });
});
```

Then maybe:

**Comment by Jnull** [comment]
you probably want something jerry-rigged like this: 
```
var user_id = 0; 
io.on('connection', function(socket){
user_id++; 
  var client = new irc.Client('localhost', 'myNick' + user_id, {
      channels: ['#webchat'],
  });

  client.addListener('message', function (from,to,message) {
    io.emit('message', message);
  });

  socket.on('disconnect', function(){
  });
});
```
If that doesn't work, you may have to get jiggy with the client object and push ever new subsequent client to an array like: 
```
var client_list_array = [];
var client_list_array.push({new irc.Client: etc...});

```

**Comment by ircer** [comment]
I fixed it by changing `io.emit('message', message);` to `socket.emit('message', message);`, so the message is sent to that socket only, not all.

**Comment by Jnull** [comment]
oh i thought it was on your ircd #messages channel, not your web application, yep that would be it then.

**Comment by ircer** [comment]
@Jnull how can I convert messages to CSS colours?

`pervena2: 10,00wb Okwaho` is an example message, how do I get the 10,00 converted to CSS colours?

**Comment by Jnull** [comment]
CSS is out of scope to node-irc, you will need to go elsewhere to find an html/css tutorial.   If your original problem has been solved, please close this and create a new issue, but only if its a node-irc issue.  Thanks!
