### ISSUE TITLE
client.send() always include : in first text

### ISSUE THREAD

**Issue by anonprophet** [martynsmith/node-irc#420]
```
case '!topgames':
client.send('s', 'chat', nick, 'Top Games :');
db.query('SELECT player, games FROM stats ORDER BY games DESC LIMIT 13', function(err, rows) {
    if (err) throw err;

    for (var i = 0; i < rows.length; i++) {
        client.send('s', 'chat', nick, i+1 + '. ' + rows[i].player + ' : ' + rows[i].games);
    };
});
break;
```
its always include `:` in first text
![screenshot_1](https://cloud.githubusercontent.com/assets/8217350/10724318/2128a2d8-7bf6-11e5-929a-2b843b863234.png)

its the debug message
```
26 Oct 15:26:22 - SEND: s chat mushi :1. miracle- : 13891
```

the message should ``1. miracle- : 13891``
not ``:1. miracle- : 13891``

how/where i can to remote that `:` ?

**Comment by moshmage** [comment]
@anonprophet we are not your personal StackOverflow __nor is this a issue__ what you are seeing is a log of what was sent  *to the server*, which is composed of a `:` character.    
    
What the SERVER sent to the user was `1. miracle- : 13891`.

**Comment by anonprophet** [comment]
@moshmage sorry, but its `:` not show if use mIRC (using /raw)
im ask , someone maybe know why `:` its show and where i can delete it

**Comment by Jnull** [comment]
@anonprophet This is only cosmetic to the debug messages, you are receiving the raw output as expected, you should be fine, but we cannot help if its not a node-irc issue. Also do you mind closing your other issue #416 before opening a new one? 

@moshmage,  i second your motion to close, but i suggest that novice requests get treated with more guidance, this was an honest mistake as oppose to someone trying to offload work to someone else.
