### ISSUE TITLE
Error Handling Improvements (all errors should gracefully fail)  

### ISSUE THREAD

**Issue by Jnull** [martynsmith/node-irc#421]
I purpose to improve error handling to prevent crashing as much as programmatically possible during normal operations.

**Comment by moshmage** [comment]
In regards to #419, shouldn't a [`case: 'NICK'`](https://github.com/martynsmith/node-irc/blob/master/lib/irc.js#L310) be fired?

On topic: Are we talking about just.. wrapping the whole thing into a `try`, `catch`?

**Comment by Jnull** [comment]
Lines: 747-753: 
```
747:            try {
                    self.emit('raw', message);
                } catch (err) {
                    if (!self.conn.requestedDisconnect) {
                        throw err;
                    }
753:           }
``` 
At a minimum what I'm thinking is we take these lines and instead of throwing an error after the hail mary, we send the error to console, and make a threshold.  If we see 3-5 errors in less then 5 seconds then we throw the err.

**Comment by moshmage** [comment]
I'd do a "lets first close all the PRs" motion before handling this refactor, but we are on the same page on this one :)

**Comment by Jnull** [comment]
Fine by me.
