### ISSUE TITLE
Add link to docs on github wiki page

### ISSUE THREAD

**Issue by Jnull** [martynsmith/node-irc#422]
Further documentation (including a complete API reference) is available in reStructuredText format in the docs/ folder of this project, or online at Read the Docs.

http://readthedocs.org/docs/node-irc/en/latest/

**Comment by moshmage** [comment]
But... these links ARE on the Github page ?..

**Comment by Jnull** [comment]
ya i copied directly from the github page: 
```
Further documentation (including a complete API reference) is available in reStructuredText format in the docs/ folder of this project, or online at Read the Docs.

http://readthedocs.org/docs/node-irc/en/latest/
```

The wiki page is currently empty..  https://github.com/martynsmith/node-irc/wiki

**Comment by moshmage** [comment]
Oh! My bad, I read "github page" and not "github WIKI page" -- Since we are using read the docs, I'm not sure what we would gain by ALSO using the Wiki though

**Comment by Jnull** [comment]
It's just a shortcut, its better then the Winchester house, with a stairwell that leads to nowhere.

**Comment by moshmage** [comment]
That, sir, is a fair point :+1:

**Comment by Jnull** [comment]
:+1:  ;)

**Comment by jirwin** [comment]
Done!
