### ISSUE TITLE
WebIRC Support

### ISSUE THREAD

**Issue by ghost** [martynsmith/node-irc#427]
I need to add WebIRC Support to our `node-irc` usage. We have built a webchat that connects to our IRC network but the problem is that we now have 100's of users connecting by the web server IP address and not their real IP address.

Before the client sends the PASS, USER or NICK commands it should send:

`WEBIRC password user hostname ip`

How can I hook in to `node-irc` so that before it sends the PASS, USER or NICK commands it sends another command?

**Comment by Jnull** [comment]
Please read/try the docs [here] (https://node-irc.readthedocs.org/en/latest/API.html#events). ask questions on channel ##node-irc  (freenode) i idle frequently there frequently.

**Comment by ircer** [comment]
@Jnull so if I hook in to `'registered'`, will my line _definitely_ be sent after it has received the `001` numeric and before anything else is sent?

**Comment by ircer** [comment]
Just realised this is already implemented but isn't mentioned in the documentation. `lib/irc.js` shows the configuration options and relevant code.

**Comment by Jnull** [comment]
@ircer What is already implemented?

**Comment by ircer** [comment]
@Jnull WebIRC Support, what this ticket is about!

https://github.com/martynsmith/node-irc/blob/master/lib/irc.js#L59-L64 are the relevant configuration lines.

It would help if this was mentioned in the documentation, so that people don't waste time implementing something that is already supported.

**Comment by ircer** [comment]
However small bug in that linked code however.

https://github.com/martynsmith/node-irc/blob/master/lib/irc.js#L639 wants `this.opt.webirc.host` but https://github.com/martynsmith/node-irc/blob/master/lib/irc.js#L59-L62 gives `user`.

https://github.com/martynsmith/node-irc/blob/master/lib/irc.js#L62 needed to be changed from `user` to `host` and it works fine.

**Comment by moshmage** [comment]
@ircer maybe PR that fix in?

**Comment by ircer** [comment]
@moshmage done.

**Comment by ircer** [comment]
Any update on getting it merged then?

**Comment by moshmage** [comment]
@ghost MR are coming in slow, @jirwin knows more about that
