### ISSUE TITLE
Add connected flag

### ISSUE THREAD

**Issue by ismell** [martynsmith/node-irc#430]
It would be nice to know if the client is connected before calling client.say(). Currently client.say() just throws away the message.

**Comment by moshmage** [comment]
I work around that "client-side"; Hook up on the "registered" event and set a client flag.
But at the speed MR are coming in, IDK if you're not better off with a fork :/

**Comment by jirwin** [comment]
I'd prefer to keep less state in the client, and have the implementer keep track of whether or not the client is connected.
