### ISSUE TITLE
how do I auto reconnect if the server goes down?

### ISSUE THREAD

**Issue by x13machine** [martynsmith/node-irc#431]
how do I auto reconnect if the server goes down? I'm using the latest version

**Comment by x13machine** [comment]
I'm an idiot, nvm. there's a connect option

**Comment by inexist3nce** [comment]
Its not documented anywhere, but you can pass `retryCount` and `retryDelay` when creating a new Client. It will automatically reconnect if the connection is dropped.

	var irc = require('irc');
	
	new irc.Client('irc.example.org', 'someone', {
		// milliseconds to wait between retries
		retryDelay: 1000,
	
		// max attempts
		retryCount: 2
	}
