### ISSUE TITLE
retryDelay not mentioned in the docs

### ISSUE THREAD

**Issue by trudheim** [martynsmith/node-irc#446]
Hi there,

The default retryDelay is set quite short (2000ms) and it can cause issues when connecting to some IRC servers that have flood and DoS protection. I needed to hunt in your code to find out what the actual option was to extend this delay. It would be nice if it was mentioned in the docs as others might run in to the same issue.

Kind regards,

/Anders

**Comment by creesch** [comment]
you could edit the documentation yourself through this file https://github.com/martynsmith/node-irc/blob/master/docs/API.rst  (don't be fooled by the github preview, if you show raw you'll see the documentation is actually in there.) and then do a pull request. 

I am however not sure how active development is as I did a pull request myself a week ago and yet have to receive a response.

**Comment by jirwin** [comment]
I've added this to the docs. Thanks!
