### ISSUE TITLE
Library never connects to server 

### ISSUE THREAD

**Issue by kamijoutouma** [martynsmith/node-irc#451]
hey guys so i wrote a script that uses your library a few months back and since the recent update your library no longer connects. i have made no changes to the script as it is the same as when it was first made and worked
https://gist.github.com/kamijoutouma/16224ead91cd25977d37

Can someone explain why code that is exactly the same with no changes just suddenly stops working?

I didn't see any changes to the docs and the code follows the docs almoust to a T. yet for some reason the node irc library doesn't even bother to even try connecting. it never even makes it to any events to even tell me what the error is.

So unless you guys made some undocumented completely broken changes i am stumped.

**Comment by jirwin** [comment]
Spent some time debugging this with @kamijoutouma and it appears the issue lies in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812708. 

Closing this as it has to do with openssl on the server and is out of the control of node-irc.

**Comment by kamijoutouma** [comment]
@jirwin Gonna note that this workaround does fix the issues. Found it after doing a bit of digging over at letsencrypt who i use for ssl anyway.

```
apt-get remove ca-certificates
apt-get autoremove
apt-get install ca-certificates
```

Viola everything is working again.
