### ISSUE TITLE
Accepting Files

### ISSUE THREAD

**Issue by IshanArya** [martynsmith/node-irc#488]
Is there a way to accept files being sent to you? I found this repo : https://github.com/Booster2ooo/irc-xdcc :, which seems to use dcc. However, I don't know how to simply accept the files a user is giving you. How can I retrieve the packid or anything else I receive from a user? If there is no way, can it be implemented?

**Comment by del6597** [comment]
node-irc has no DCC implementation so it would need to be written in order for you to receive or send files to a user.

According to wikipedia there is no RFC defining DCC protocol either.
https://en.wikipedia.org/wiki/Direct_Client-to-Client

**Comment by john-patterson** [comment]
I found this repo when looking into what it would take to add DCC into node-irc.

https://github.com/tritium21/node-irc-dcc

May prove useful to others in this spot.

**Comment by IshanArya** [comment]
Actually, the irc-xdcc repo I linked ended up working to solve my problem [https://github.com/Booster2ooo/irc-xdcc](https://github.com/Booster2ooo/irc-xdcc). I just had to make "acceptUnpooled" to true.

Thank you for your help!
