### ISSUE TITLE
Client.say/notice ect

### ISSUE THREAD

**Issue by Gaz492** [martynsmith/node-irc#509]
I dont know if im doing something wrong but if i export client and try to use client.say(channel, message) in another file with client required i get client.say is not a function

**Comment by john-patterson** [comment]
Cannot recreate without more detail. 

Here is my `client.js` file:
```javascript
let irc = require('irc');

let defaultConfig = {
  server: 'us.undernet.org',
  nick: 'exportClientTest',
  chan: '#exportClientTest'
};

let ircClient = new irc.Client(defaultConfig.server, defaultConfig.nick, {
  channels: [defaultConfig.chan],
});

ircClient.addListener('error', (msg) => {
  console.error('[ERR] ' + msg);
});

module.exports = {
  client: ircClient,
  channel: defaultConfig.chan
};
```

and here is the file that uses it:

```javascript

let {client, channel} = require('./client');

setInterval(() => {
  client.say(channel, 'Hello, World!');
}, 10000);
```

Here is the result:
![irc channel showing Hello World post](https://user-images.githubusercontent.com/17716252/27256428-060828fe-537a-11e7-8640-f7ddbb9d006f.png)
