### ISSUE TITLE
How to get the Server Name

### ISSUE THREAD

**Issue by madprops** [martynsmith/node-irc#549]
I can't find a way to get the 'real server name' of a server. For instance "Freenode". Nothing regarding it comes up in the registered event message and checking the documentation I can't find nothing. Where can I look for it? Thanks.

**Comment by wilsonmfg** [comment]
IRC doesn't have such a thing.  you might be able to parse it from the MOTD or one of the other raw event data

**Comment by madprops** [comment]
Makes sense. Now that I think about it the user would store the name on the server settings anyway. Thanks.
