### ISSUE TITLE
QUIT, KILL removes users from user list before processing event hooks

### ISSUE THREAD

**Issue by Acubed** [martynsmith/node-irc#73]
The default 'raw' event hook is executed before anything else, which removes. It emits a 'quit' event which lists the removed users, however other commands (KILL, NICK) have no way of knowing what the affected channels are. Additionally with the current 'quit' event there is no way to get the raw parsed packet AND the list of channels the user was in. Perhaps the data structures should not be modified until all event hooks have been fully processed.

**Comment by Jnull** [comment]
Since #242 has been closed, i believe events were added in a previous code rewrite.

I suggest this be closed.
