### ISSUE TITLE
Detect ping timeout

### ISSUE THREAD

**Issue by csimi** [martynsmith/node-irc#76]
I think there's no ping timeout detection in the library right now. I waited for around 5 minutes to see if something happens but nothing did.

Steps to reproduce:
1. Connect to a server.
2. Disconnect from the internet (disconnect button on router webui for example).
3. Reconnect to internet.
4. The library doesn't detect that you got ping timeouted from the server, therefore it doesn't even try to reconnect.

I'm gonna temporarily fix this issue by manually pinging the server every few minutes but this puts (a minimal amount from my single bot) extra stress on the server so you might want to find something more elegant.
    15 Dec 21:59:39 - SEND: PING :PONG
    15 Dec 21:59:39 - Connection got "close" event
    15 Dec 21:59:39 - Disconnected: reconnecting
    15 Dec 21:59:39 - Waiting 2000ms before retrying

**Comment by Jnull** [comment]
Please Close this. Ping timeout support was added from #176

**Comment by damianb** [comment]
@Jnull [That does not seem to be true](https://github.com/martynsmith/node-irc/pull/176#issuecomment-31161955)

**Comment by Jnull** [comment]
Oh okay, thanks, support was lost due to the code reconstruction.  #214 should be reopened.

**Comment by jirwin** [comment]
Done.

**Comment by JorgenPhi** [comment]
This really needs to be implemented.

**Comment by philip-peterson** [comment]
I'm working on this now, should be done by the end of the night.

**Comment by Jnull** [comment]
Awesome!  :+1:

**Comment by jirwin** [comment]
Fixed in #418.
